### ISSUE TITLE
Add levels

### ISSUE THREAD

**Issue by Jake-Shadle** [gwihlidal/smush-rs#2]
Most of these compression algorithms expose some notion of a level for adjusting compression time vs quality, so having a nice way of expressing that would be good to have. Would probably be easiest just to expose basic categories that map to the individual algorith, eg. Fastest, Default, Highest or something along those lines.

**Comment by gwihlidal** [comment]
Yup! Was thinking along those lines - some abstract levels that map over to each compressors levels. Will add that in.

**Comment by gwihlidal** [comment]
Implemented in v0.1.3!
