### ISSUE TITLE
Rename functions to just encode / decode?

### ISSUE THREAD

**Issue by repi** [gwihlidal/smush-rs#3]
The `_data` suffix on the function names feels quite redundant.

Not a major issue though

**Comment by gwihlidal** [comment]
Yeah, am wondering about that. I do plan to add a trait\reader based version, which would need a unique name, so felt that encode_data vs encode_stream or something would be nice, but not really set on a particular convention. Thoughts?

**Comment by gwihlidal** [comment]
Could also rename encode_data -> encode_slice, decode_data -> decode_slice to be more specific.

**Comment by gwihlidal** [comment]
Thanks for the feedback!

Changed in v0.1.3
